[build]
builder = "NIXPACKS"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
# healthcheckPath = "/api/health/"  # 完全無効化
# healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 