[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT:-8000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# 永続ストレージの設定
[[deploy.volumes]]
source = "aozora-data"
target = "/code/RAG_test" 