[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py check --verbosity=2 && python manage.py migrate && echo 'Migration completed successfully' && sleep 30"
healthcheckPath = "/api/health/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 