[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate"
healthcheckPath = "/api/health/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 