[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
# healthcheckPath = "/api/health/"  # 完全無効化
# healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 