# Generated by Django 4.2.7 on 2025-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AozoraBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, unique=True, verbose_name='作品ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品名')),
                ('author', models.CharField(max_length=100, verbose_name='著者名')),
                ('author_id', models.CharField(max_length=20, verbose_name='著者ID')),
                ('card_url', models.URLField(max_length=300, verbose_name='図書カードURL')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='公開日')),
                ('access_count', models.IntegerField(default=0, verbose_name='アクセス数')),
                ('description', models.TextField(blank=True, verbose_name='あらすじ')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='ランキング')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '青空文庫作品',
                'verbose_name_plural': '青空文庫作品',
                'ordering': ['-access_count', '-ranking'],
            },
        ),
    ]
